# Generated by Django 5.1.4 on 2025-01-22 23:53

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('IdCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDepartamento',
            fields=[
                ('IdEstadoDpto', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('IdFormato', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('IdPiso', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('IdProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('Documento', models.CharField(max_length=50, unique=True, verbose_name='Documento')),
                ('RazonSocial', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electrónico')),
                ('FechaRegistro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('IdRol', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Documento', models.CharField(max_length=30, unique=True, verbose_name='Documento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('cambiarClave', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('IdRol', models.ForeignKey(db_column='IdRol', on_delete=django.db.models.deletion.CASCADE, to='core.rol', verbose_name='Rol')),
            ],
            options={
                'db_table': 'Usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('IdDpto', models.AutoField(primary_key=True, serialize=False)),
                ('Departamento', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electrónico')),
                ('FechaRegistro', models.DateField(auto_now_add=True)),
                ('JefeDpto', models.ForeignKey(db_column='IdJefeDpto', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Jefe de Departamento')),
                ('IdEstadoDpto', models.ForeignKey(db_column='IdEstadoDpto', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estadodepartamento')),
                ('IdPiso', models.ForeignKey(db_column='IdPiso', on_delete=django.db.models.deletion.CASCADE, to='core.piso', verbose_name='Piso')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('IdDespacho', models.AutoField(primary_key=True, serialize=False)),
                ('FechaRegistro', models.DateField(auto_now_add=True)),
                ('IdDpto', models.ForeignKey(db_column='IdDpto', on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
                ('Usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrador')),
            ],
        ),
        migrations.CreateModel(
            name='Mim',
            fields=[
                ('IdMIM', models.AutoField(primary_key=True, serialize=False)),
                ('Cod', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('Nombre', models.CharField(max_length=100)),
                ('Stock', models.IntegerField(default=0)),
                ('Reservado', models.IntegerField(default=0)),
                ('IdCategoria', models.ForeignKey(db_column='IdCategoria', on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Categoría')),
                ('IdFormato', models.ForeignKey(db_column='IdFormato', on_delete=django.db.models.deletion.CASCADE, to='core.formato', verbose_name='Formato')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CantidadEntregada', models.IntegerField()),
                ('IdDespacho', models.ForeignKey(db_column='IdDespacho', on_delete=django.db.models.deletion.CASCADE, to='core.despacho')),
                ('IdMIM', models.ForeignKey(db_column='IdMIM', on_delete=django.db.models.deletion.CASCADE, to='core.mim')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('IdSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('FechaRegistro', models.DateField(auto_now_add=True)),
                ('IdDpto', models.ForeignKey(db_column='IdDpto', on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
                ('Usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrador')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CantidadSolicitada', models.IntegerField()),
                ('IdMIM', models.ForeignKey(db_column='IdMIM', on_delete=django.db.models.deletion.CASCADE, to='core.mim')),
                ('IdSolicitud', models.ForeignKey(db_column='IdSolicitud', on_delete=django.db.models.deletion.CASCADE, to='core.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('IdSuministro', models.AutoField(primary_key=True, serialize=False)),
                ('Lote', models.CharField(max_length=50)),
                ('FechaRegistro', models.DateField(auto_now_add=True)),
                ('Proveedor', models.ForeignKey(db_column='IdProveedor', on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
                ('Usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrador')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSuministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaVencimiento', models.DateField(default='2199-12-31', verbose_name='Fecha de Vencimiento')),
                ('Cantidad', models.IntegerField()),
                ('IdMIM', models.ForeignKey(db_column='IdMIM', on_delete=django.db.models.deletion.CASCADE, to='core.mim')),
                ('IdSuministro', models.ForeignKey(db_column='IdSuministro', on_delete=django.db.models.deletion.CASCADE, to='core.suministro')),
            ],
        ),
    ]
